#!/bin/bash

hosts_file=$1

while read -r hosts
do
	name=${hosts/\//_}
	mkdir $name
	nmap -vv -n -sn -PE -oA $name/livehosts_1_$name $hosts
	nmap -vv -n -sn -PO -oA $name/livehosts_2_$name $hosts
	nmap -vv -n -sn -PP -oA $name/livehosts_3_$name $hosts
	nmap -vv -n -sn -Pn -oA $name/livehosts_4_$name $hosts
	
	grep "Up" $name/livehosts_1_$name.gnmap| awk '{print$ 2}' >> $name/tmp
	grep "Up" $name/livehosts_2_$name.gnmap| awk '{print$ 2}' >> $name/tmp
	grep "Up" $name/livehosts_3_$name.gnmap| awk '{print$ 2}' >> $name/tmp
	grep "Up" $name/livehosts_4_$name.gnmap| awk '{print$ 2}' >> $name/tmp

	cat $name/tmp | sort -u >> $name/all_live_hosts_$name.txt
	rm $name/tmp
	cat $name/all_live_hosts_$name.txt >> all_live_hosts.txt
	cat all_live_hosts.txt | sort -u > .tmp
	cat .tmp > all_live_hosts.txt
	rm .tmp
	aliive=`wc -l < all_live_hosts.txt`
done < $hosts_file
